name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Inject Environment Variables
      run: |
        # Создаем файл с переменными окружения для браузера
        cat > env-config.js << EOF
        window.CLIENT_ID = '${{ secrets.CLIENT_ID }}';
        window.CLIENT_SECRET = '${{ secrets.CLIENT_SECRET }}';
        window.PROJECT_ID = '${{ secrets.PROJECT_ID }}';
        window.GOOGLE_DRIVE_FOLDER_ID = '${{ secrets.GOOGLE_DRIVE_FOLDER_ID }}';
        window.GOOGLE_DRIVE_FOLDER_URL = '${{ secrets.GOOGLE_DRIVE_FOLDER_URL }}';
        EOF
        
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: '.'
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
